# Generated by Django 3.1.1 on 2021-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_testclasser_videodone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodone',
            name='id',
        ),
        migrations.AlterField(
            model_name='videodone',
            name='video_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubekey',
            name='banned',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
