# Generated by Django 3.1.6 on 2021-02-20 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20210202_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber_count',
            field=models.CharField(blank=True, default='--', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='video_count',
            field=models.CharField(blank=True, default='--', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='view_count',
            field=models.CharField(blank=True, default='--', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='custom_id',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='facebook',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='instagram',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='others_links',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='parsed_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 20, 10, 0, 25, 833131, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='telegram',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='twitter',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='vk',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='videodone',
            name='comments_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videodone',
            name='parsed_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 20, 10, 0, 29, 474394, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='channel_pk',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), to='parsing.channel'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='custom_url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='published_at',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_count',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='video_count',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='view_count',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='UserCommentsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(default='', max_length=200, unique=True)),
                ('user_id', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='')),
                ('comment_original', models.TextField(default='')),
                ('video_id', models.CharField(default='', max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('published', models.CharField(default='', max_length=200)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.ForeignKey(default=1, on_delete=models.SET(0), to='parsing.channel')),
            ],
        ),
        migrations.CreateModel(
            name='PreloadedStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.BigIntegerField(default=0)),
                ('comments_all_count', models.BigIntegerField(default=0)),
                ('commenters_count', models.BigIntegerField(default=0)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.channel', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreLoadedHourStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.BigIntegerField(default=0)),
                ('subscribers', models.BigIntegerField(default=0)),
                ('videos', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.channel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPerVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_count', models.CharField(max_length=255)),
                ('like_count', models.CharField(max_length=200)),
                ('dislike_count', models.CharField(max_length=200)),
                ('view_count', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=200)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.ForeignKey(on_delete=models.SET(0), to='parsing.channel')),
            ],
        ),
    ]
