# Generated by Django 3.1.6 on 2021-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20210220_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBannedKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videodone',
            name='comments_parsed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubscriberWithoutChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(max_length=200, unique=True)),
                ('from_channel_id', models.ForeignKey(on_delete=models.SET(0), to='parsing.channel')),
            ],
        ),
    ]
