# Generated by Django 3.1.6 on 2021-03-24 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_auto_20210220_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='image_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriberwithoutchannel',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentpervideo',
            name='video_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ImageWithSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=255)),
                ('uploaded', models.BooleanField(default=False)),
                ('subscriber_id', models.ForeignKey(on_delete=models.SET(0), to='parsing.subscriber', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_done', models.IntegerField(default=0)),
                ('subscribers', models.BigIntegerField(default=0)),
                ('comments_all', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('commenters', models.BigIntegerField(default=0)),
                ('sub_percent', models.FloatField(default=0.0)),
                ('video_percent', models.FloatField(default=0.0)),
                ('comment_percent', models.FloatField(default=0.0)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.channel', unique=True)),
            ],
        ),
    ]
