import time

import aiohttp
import asyncio
import json
import os
from aiohttp import ClientSession

LIST_ISBN = [
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YEQ3T0s_utM&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=054smjVFy8A&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=07u2pW4hT5w&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YEQ3T0s_utM&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=054smjVFy8A&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=07u2pW4hT5w&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YEQ3T0s_utM&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=054smjVFy8A&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=07u2pW4hT5w&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YEQ3T0s_utM&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=054smjVFy8A&maxResults=100&order=relevance&key=AIzaSyDyIbkGEOqSv3QEfrooQoQcK488yLWDrj8",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=07u2pW4hT5w&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YEQ3T0s_utM&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=054smjVFy8A&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=07u2pW4hT5w&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
    "https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=09jklFC_BFk&maxResults=100&order=relevance&key=AIzaSyCg7K6yVStkeiWXrMRlK9_ewsv8E377GZo",
]
count = 0


async def run_program(url, session, index):
    # st = time.monotonic()
    try:
        response = await session.request(method='GET', url=url, timeout=5, allow_redirects=False)
        print(response)
    except Exception as e:
        print(e)

    print(index)

    # print("end req", time.monotonic() - st)


async def starter():
    print(len(LIST_ISBN))
    async with ClientSession() as session:
        st = time.monotonic()
        await asyncio.gather(*[run_program(isbn, session, index) for index, isbn in enumerate(LIST_ISBN)])
        print("end", time.monotonic() - st)


loop = asyncio.get_event_loop()
loop.run_until_complete(starter())
# loop.run_forever()
# asyncio.run(starter())
